# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: > 
      wget https://repo.anaconda.com/miniconda/Miniconda3-py310_22.11.1-1-Linux-x86_64.sh -O /tmp/Minconda3.sh &&
      bash /tmp/Minconda3.sh -b -p /workspace/miniconda3 &&
      echo "export PATH=/workspace/miniconda3/bin:$PATH" >> ~/.bashrc &&
      source ~/.bashrc
    command: >
      conda env create -n parrot_env -f envs_cpu.yaml && 
      source activate parrot_env &&
      cd web_app &&
      python app.py

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview
