database_path: '../dataset/source_dataset/USPTO_suzuki_final'
database_name: 'USPTO_suzuki_condition'
train_from_checkpoints: ./model/baseline_train_1_USPTO_condition
model_path: ./model
model_name: 'baseline_train_1_USPTO_suzuki_final_transfer_from_USPTO_condition'
use_temperature: false
gpu: 0
lr: 0.0030
batch_size: 256
epochs: 50
h_dim: 1000
dropout_rate: 0.5